# Generated by Django 5.0.6 on 2026-09-26 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_disappearing_and_screen_protect"),
        ("users", "0005_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachment",
            name="height",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attachment",
            name="width",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="SpecialistChatSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accept_client_files", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "specialist",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_settings",
                        to="users.psychologistprofile",
                    ),
                ),
            ],
            options={
                "db_table": "chat_specialist_settings",
            },
        ),
    ]
