# Generated by Django 5.0.6 on 2026-05-22 19:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("consultations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "yookassa_payment_id",
                    models.CharField(blank=True, max_length=100, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает"),
                            ("waiting_for_capture", "Ожидает захвата"),
                            ("succeeded", "Успешен"),
                            ("cancelled", "Отменён"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("amount_rub", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "psychologist_payout_rub",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "platform_fee_rub",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("confirmation_url", models.URLField(blank=True)),
                ("idempotency_key", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("captured_at", models.DateTimeField(blank=True, null=True)),
                ("refunded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment",
                        to="consultations.consultationsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Платёж",
                "db_table": "payments_payment",
            },
        ),
        migrations.CreateModel(
            name="Payout",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("yookassa_payout_id", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Запланирована"),
                            ("processing", "В обработке"),
                            ("succeeded", "Выполнена"),
                            ("failed", "Ошибка"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("amount_rub", models.DecimalField(decimal_places=2, max_digits=10)),
                ("scheduled_at", models.DateTimeField()),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "payment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payout",
                        to="payments.payment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Выплата",
                "db_table": "payments_payout",
            },
        ),
    ]
