# Generated by Django 5.0.6 on 2026-05-22 19:12

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email_hash",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("alias", models.CharField(max_length=40, unique=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("client", "Клиент"),
                            ("psychologist", "Психолог"),
                            ("admin", "Администратор"),
                        ],
                        default="client",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользователь",
                "db_table": "users_user",
            },
        ),
        migrations.CreateModel(
            name="PsychologistProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("encrypted_full_name", models.BinaryField(blank=True, null=True)),
                ("encrypted_diploma_number", models.BinaryField(blank=True, null=True)),
                ("encrypted_phone", models.BinaryField(blank=True, null=True)),
                ("display_name", models.CharField(max_length=80)),
                ("bio", models.TextField(blank=True, max_length=1200)),
                ("specializations", models.JSONField(default=list)),
                ("languages", models.JSONField(default=list)),
                (
                    "session_rate_rub",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает проверки"),
                            ("approved", "Верифицирован"),
                            ("rejected", "Отклонён"),
                            ("suspended", "Приостановлен"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("yookassa_account_id", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="psychologist_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_psychologists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Профиль психолога",
                "db_table": "users_psychologist_profile",
            },
        ),
        migrations.CreateModel(
            name="PsychologistSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.SmallIntegerField(
                        choices=[
                            (0, "Пн"),
                            (1, "Вт"),
                            (2, "Ср"),
                            (3, "Чт"),
                            (4, "Пт"),
                            (5, "Сб"),
                            (6, "Вс"),
                        ]
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "psychologist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_slots",
                        to="users.psychologistprofile",
                    ),
                ),
            ],
            options={
                "db_table": "users_schedule",
                "unique_together": {("psychologist", "weekday", "start_time")},
            },
        ),
    ]
