# Generated by Django 5.0.6 on 2026-09-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="alias_changed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
