[build]
builder = "dockerfile"
dockerfilePath = "railway.Dockerfile"

[deploy]
healthcheckPath = "/api/v1/health/"
healthcheckTimeout = 60
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
