# Generated by Django 5.0.6 on 2026-05-22 19:12

import apps.sessions.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConsultationSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Создана"),
                            ("awaiting_payment", "Ожидает оплаты"),
                            ("paid", "Оплачена"),
                            ("in_progress", "Идёт сессия"),
                            ("completed", "Завершена"),
                            ("cancelled", "Отменена"),
                            ("refunded", "Возврат"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("scheduled_at", models.DateTimeField()),
                ("duration_minutes", models.PositiveSmallIntegerField(default=50)),
                (
                    "session_token",
                    models.CharField(
                        db_index=True,
                        default=apps.sessions.models._generate_session_token,
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("token_expires_at", models.DateTimeField(blank=True, null=True)),
                ("token_used", models.BooleanField(default=False)),
                (
                    "webrtc_room_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("amount_kopecks", models.PositiveIntegerField()),
                ("psychologist_payout_kopecks", models.PositiveIntegerField(default=0)),
                ("platform_fee_kopecks", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Сессия консультации",
                "db_table": "sessions_consultation",
            },
        ),
        migrations.CreateModel(
            name="SessionEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("token_created", "Токен создан"),
                            ("payment_initiated", "Платёж инициирован"),
                            ("payment_confirmed", "Платёж подтверждён"),
                            ("room_opened", "Комната открыта"),
                            ("participant_joined", "Участник подключился"),
                            ("participant_left", "Участник отключился"),
                            ("session_ended", "Сессия завершена"),
                            ("payout_sent", "Выплата отправлена"),
                        ],
                        max_length=30,
                    ),
                ),
                ("metadata", models.JSONField(default=dict)),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "sessions_event",
                "ordering": ["occurred_at"],
            },
        ),
        migrations.CreateModel(
            name="SessionNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("encrypted_content", models.BinaryField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "sessions_note",
            },
        ),
    ]
