# Generated by Django 5.0.6 on 2026-05-22 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("consultations", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="consultationsession",
            name="client",
            field=models.ForeignKey(
                limit_choices_to={"role": "client"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="client_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="consultationsession",
            name="psychologist_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="psychologist_sessions",
                to="users.psychologistprofile",
            ),
        ),
        migrations.AddField(
            model_name="sessionevent",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="consultations.consultationsession",
            ),
        ),
        migrations.AddField(
            model_name="sessionnote",
            name="session",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="note",
                to="consultations.consultationsession",
            ),
        ),
        migrations.AddIndex(
            model_name="consultationsession",
            index=models.Index(
                fields=["status", "scheduled_at"], name="sessions_co_status_d1924a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="consultationsession",
            index=models.Index(
                fields=["webrtc_room_id"], name="sessions_co_webrtc__18c66f_idx"
            ),
        ),
    ]
