# Generated by Django 5.0.6 on 2026-09-26 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0005_alter_user_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpecialistSelfie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("frame1_enc", models.BinaryField()),
                ("frame2_enc", models.BinaryField()),
                ("challenge", models.CharField(max_length=20)),
                ("taken_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_selfie",
                        to="users.psychologistprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Селфи для проверки",
                "db_table": "verification_selfie",
            },
        ),
    ]
